iamblooddonor/blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

iamblooddonor/blooddonor/urls.py
from django.urls import path
from . import views
# BloodDonorApp's URL
urlpatterns = [
    path("",views.index, name='home'),
    path("about/",views.about, name='about'),
    path("contact/",views.contact, name='contact'),
    path('connect/', views.connect_org, name='connect-organization'),
    path("photogallery",views.photogallery, name="gallery"),
    path('photo_upload/', views.photo_upload, name='photo-upload'),
    path('opinion/', views.opinion, name='opinion'),
    path('blood_request/', views.blood_request, name='blood-request'),
    path("donation/",views.donation, name='donation'),
]

iamblooddonor/iamblooddonor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# All App URL
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blooddonor.urls")),
    path("donor/", include("donor_profile.urls")),
    path("blog/", include("blog.urls")),
    # path("campblog/", include("campblog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

iamblooddonor/blooddonor/models.py
from django.db import models
from django.core.validators import URLValidator
from PIL import Image



class DonationProcess(models.Model):
    image       = models.ImageField()
    heading     = models.CharField(max_length=200)
    content     = models.TextField() 
    created_at  = models.DateTimeField(auto_now=True) 
    updated_at  = models.DateTimeField(auto_now=True)

class TeamMember(models.Model):
    image     = models.ImageField(default='team_member_photo')
    profile_name    = models.CharField(max_length=250)
    position        = models.CharField(max_length=200)
    facebook_link = models.CharField(validators=[URLValidator()], max_length=120)
    instagram_link = models.CharField(validators=[URLValidator()], max_length=120)
    twitter_link = models.CharField(validators=[URLValidator()], max_length=120)
    googleplus_link = models.CharField(validators=[URLValidator()], max_length=120)
    linkedin_link = models.CharField(validators=[URLValidator()], max_length=120)
    github_link = models.CharField(validators=[URLValidator()], max_length=120)

    def __str__(self):
        return self.profile_name

    def save(self):
        super().save()
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class PhotoGallery(models.Model):
    image_author = models.CharField(max_length=250)
    image_title = models.CharField(max_length=250)
    image = models.ImageField(default='gallery')
    upload_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.image_title

    class Meta:
        ordering = ['-upload_time']



class Opinion(models.Model):
    name = models.CharField(max_length=200)
    text = models.TextField()
    position = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)



class Contact(models.Model):
    name = models.CharField(max_length=120)
    email = models.EmailField()
    message = models.TextField()


class BloodRequestMessage(models.Model):
    name = models.CharField(max_length=150)
    date = models.DateTimeField(auto_now=True)
    text = models.TextField(blank=True, null=True)


# Connected Organizations
class ConnectedOrganization(models.Model):
    choice_type = (
        ('Sponsor', 'Sponsor'),
        ('Organization', 'Organization')
    )
    organization_name = models.CharField(max_length=250)
    join_as = models.CharField(max_length=250, choices=choice_type)
    logo = models.FileField()
    web_link = models.CharField(validators=[URLValidator()], max_length=120)
    facebook_link  = models.CharField(validators=[URLValidator()], max_length=120)

    def __str__(self):
        return self.organization_name

class News(models.Model):
    name = models.CharField(max_length=250)
    news_text = models.TextField()
    created_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

iamblooddonor/donor_profile/models.py
from django.db import models
from django.core.validators import URLValidator
from django.contrib.auth.models import User
from PIL import Image

# BloodGropModel
class BloodGroupName(models.Model):
    blood_group = models.CharField(max_length=20)

    def __str__(self):
        return self.blood_group

# DonorProfileModel
class Profile(models.Model):
    gender_choices = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others')
    )
    donation_capability_choices = (
        ('Yes', 'Yes'),
        ('No', 'No')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    date_of_birth = models.DateField(blank=True, null=True)
    weight = models.IntegerField(blank=True, null=True)
    blood_group = models.ForeignKey(BloodGroupName, on_delete=models.CASCADE)
    location = models.CharField(max_length=120)
    institute = models.CharField(max_length=120, blank=True, null=True)
    occupation = models.CharField(max_length=120, blank=True, null=True)
    last_donation_date = models.DateField(blank=True, null=True)
    last_donation_place = models.CharField(max_length=50, blank=True, null=True)
    donation_capability = models.CharField(max_length=3, choices=donation_capability_choices, blank=True, null=True)
    phone = models.CharField(max_length=12)
    donation_times = models.IntegerField()
    facebook_link = models.CharField(validators=[URLValidator()], max_length=120, blank=True, null=True)
    image = models.ImageField(upload_to='profile_pics')

    def __str__(self):
        return self.name


    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

iamblooddonor/blooddonor/forms.py
from django import forms
from .models import (
    Contact,
    PhotoGallery,
    Opinion,
    ConnectedOrganization,
    BloodRequestMessage
)

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

class PhotoUpload(forms.ModelForm):
    class Meta:
        model = PhotoGallery
        fields = '__all__'


class OpinionForm(forms.ModelForm):
    class Meta:
        model = Opinion
        fields = '__all__'


class BloodRequestForm(forms.ModelForm):
    class Meta:
        model = BloodRequestMessage
        fields = '__all__'

class ConnectOrganizationForm(forms.ModelForm):
    class Meta:
        model = ConnectedOrganization
        fields = '__all__'

iamblooddonor/blooddonor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
# All Models For BloodDonor App
from . models import (
    DonationProcess,
    PhotoGallery,
    TeamMember,
    DonationProcess,
    Opinion,
    BloodRequestMessage,
    ConnectedOrganization,
    News

)
from blog.models import BlogPost
# All Forms For BloodDonor App
from .forms import (
    ContactForm,
    PhotoUpload,
    OpinionForm,
    ConnectOrganizationForm,
    BloodRequestForm
)
from donor_profile.models import BloodGroupName


# HomeView
def index(request):
    posts = BlogPost.objects.all().order_by('-posted_on')[:2]
    photos = PhotoGallery.objects.all().order_by('-upload_time')
    members = TeamMember.objects.all()
    all_process = DonationProcess.objects.all()
    groups = BloodGroupName.objects.all()
    opinions = Opinion.objects.all().order_by('-created_at')
    blood_requests = BloodRequestMessage.objects.all().order_by('-date')[:3]
    organizations = ConnectedOrganization.objects.all().order_by('-organization_name')
    all_news = News.objects.all().order_by('-created_on')[:1]



    context = {
        'posts':posts,
        'photos': photos,
        'members': members, 
        'all_process': all_process,
        'groups': groups,
        'opinions': opinions,
        'blood_requests': blood_requests,
        'organizations': organizations,
        'all_news': all_news
    }
    return render(request, 'blooddonor/index.html', context)


# AboutView
def about(request):
    members = TeamMember.objects.all()
    context = {
        'members': members
    }
    return render(request, 'blooddonor/about.html')

# ContactView
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your message has been sent successfully!')
            return redirect('home')
    else:
        form = ContactForm()
    context = {
        'form': form
    }
    return render(request, 'blooddonor/contact.html', context)


# DonorOpinionView For Posting Donor Opinion
def opinion(request):
    if request.method == 'POST':
        form = OpinionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your Opinion has been published successfully!')
            return redirect('home')
    else:
        form = OpinionForm()
    context = {
        'form':form
    }
    return render(request, 'blooddonor/opinion.html', context)

# PhotoGalleryView For Storing Donor's Photo
def photogallery(request):
    photos = PhotoGallery.objects.all()
    context = {
        'photos':photos
    }
    return render(request, 'blooddonor/gallery.html', context)

# PhotoUploadView For Uploading Photo
def photo_upload(request):
        if request.method == 'POST':
            form = PhotoUpload(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, f'Your photo has been uploaded successfully!')
                return redirect('home')
        else:
            form = PhotoUpload()
        context = {
            'form': form,
        }
        return render(request, 'blooddonor/photo_upload.html', context)

# ConnectOrganizationView
def connect_org(request):
    if request.method == 'POST':
        form = ConnectOrganizationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your organization has been connected with us successfully!')
            return redirect('home')
    else:
        form = ConnectOrganizationForm()
    context = {
        'form': form,
    }
    return render(request, 'blooddonor/connect_organization.html', context)

# BloodRequest
def blood_request(request):
    if request.method == 'POST':
        form = BloodRequestForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your Message has been published! Hopefully You Will Get The ExpectedBlood Donor')
            return redirect('home')
    else:
        form = BloodRequestForm()
    context = {
        'form': form,
    }
    return render(request, 'blooddonor/blood_request.html', context)




def donation(request):
    process = DonationProcess.objects.all() 
    context = {
        'process':process
    }
    return render(request, 'blooddonor/index.html', context)

iamblooddonor/blooddonor/templates/blooddonor/about.html
{% extends 'blooddonor/base.html' %}
{% load static %}
{% block content %}
<!-- team part start  -->
    <section class="team_part">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="about_content text-center">
                        <img src="{% static 'blooddonor/images/line.png' %}" id="team_line" alt="">
                        <h2>I'mBloodDonor <span>Team</span></h2>
                        <img src="{% static 'blooddonor/images/line.png' %}" alt="">
                        <h4>I'mBloodDonor team works hard for providing an easiest way of searching blood! This is not a commercial project. So feel free to improve this site.<br>
                        </h4>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center team_slider">
                <!--  Team one start  -->
                {% for member in members %}
                <div class="col-lg-5 col-md-5">
                    <div class="team_member">
                        <div class="row">
                            <div class="col-lg-5 col-sm-6 col-10">
                                <div class="team_img">
                                    <img src="{{ member.image.url }}" class="img-fluid" alt="">
                                </div>
                            </div>
                            <div class="col-lg-6 col-sm-6 col-12">
                                <div class="member_details">
                                    <h2>{{ member.profile_name }}</h2>
                                    <h3>{{ member.position }}</h3>
                                    <div class="link_icon">
                                        <a href="{{ member.facebook_link }}" target="_blank"><i class="fab fa-facebook-f"></i></a>
                                        <a href="{{ member.instagram_linnk }}" target="_blank"><i class="fab fa-instagram"></i></a>
                                        <a href="{{ member.twitter_linnk }}" target="_blank"><i class="fab fa-twitter"></i></a>
                                        <a href="{{ member.linkedin_link }}" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                                        <a href="{{ member.github_link }}" target="_blank"><i class="fab fa-github"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                 <!--  Team one end  -->
            </div>
        </div>
    </section>
    <!-- team part end  -->

{% endblock content %}

iamblooddonor/blooddonor/templates/blooddonor/blood_groups.html
{% extends "blooddonor/base.html" %}
{% block content %}
     <!--BLOOD GROUPS BLOCK START  -->
    <section class="cta-section-1">
        <div class="container">
            <div class="row justify-content-between">
                 <div class="col-md-8">
                     <h2 class="text-center">Instructions</h2>
                      <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Latest Posts</li>
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                      </ul>
                 </div>
                <div class="col-md-4">
                    <h2 class="section-heading text-center">Blood Groups</h2>

                   <table class="table table-bordered table-hover ">
                    <thead>
                    {% for group in groups %}
                        <tr class="text-center">
                            <td class="table-bg"> <a href="{% url 'donor-list' group.blood_group%}">Number of {{ group.blood_group }} Blood Donor({{ group.profile_set.count }})</a></td>
                        </tr>
                    {% endfor %}
                    </thead>
                </table>
                </div>
                </div>
            </div>
    </section>
{% endblock content %}

iamblooddonor/blooddonor/templates/blooddonor/blood_request.html
{% extends 'blooddonor/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-12 pt-5 pb-5">
            <div class="content-section">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4 text-center">
                                    <h3 class="py-4">Blood Request Messages</h3>
                                    <hr>
                                </legend>
                                {{ form|crispy}}
                            </fieldset>
                            <div class="form-group">
                                <button type="submit" class="btn btn-custom">Post</button>
                            </div>
                        </form>
            </div>
                </div>
            </div>
            </div>
{% endblock content %}

iamblooddonor/blooddonor/templates/blooddonor/connect_organization.html
{% extends 'blooddonor/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-12 pt-5 pb-5">
            <div class="content-section">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4 text-center display-4">
                                    <h3>Connect With Us Today</h3>
                                </legend>
                                {{ form|crispy}}
                            </fieldset>
                            <div class="form-group">
                                <button type="submit" class="btn btn-custom">Connect</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
{% endblock content %}

iamblooddonor/blooddonor/templates/blooddonor/contact.html
{% extends 'blooddonor/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-12 pb-5 pt-5">
            <div class="content-section">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4 text-center display-4">
                                    <h3 class="py-4">Contact Us</h3>
                                    <hr>
                                </legend>
                                {{ form|crispy}}
                            </fieldset>
                            <div class="form-group">
                                <button type="submit" class="btn btn-custom">Send</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
            </div>
{% endblock content %}

iamblooddonor/blooddonor/templates/blooddonor/footer.html
{% load static %}
    <!-- START FOOTER  -->
    <footer>
            <section class="footer-widget-area footer-widget-area-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="about-footer">
                                <div class="row">
                                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                        <img src="{% static 'blood_donor/images/logo.png' %}" alt="" />
                                    </div> <!--  end col-lg-3-->
                                    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                                        <p>
                                            We are world largest and trustful blood donation center. We have been working
                                            since 1973 with a prestigious vision to helping patient to provide blood.
                                            We are working all over the world, organizing blood donation campaign to grow
                                            awareness among the people to donate blood.
                                        </p>
                                    </div> <!--  end .col-lg-9  -->
                                </div> <!--  end .row -->
                            </div> <!--  end .about-footer  -->
                        </div> <!--  end .col-md-12  -->
                    </div> <!--  end .row  -->
                    <div class="row">
                        <div class="col-md-4 col-sm-6 col-xs-12">
                            <div class="footer-widget">
                                <div class="sidebar-widget-wrapper">
                                    <div class="footer-widget-header clearfix">
                                        <h3>Subscribe Us</h3>
                                    </div>
                                    <p>Signup for regular newsletter and stay up to date with our latest news.</p>
                                    <div class="footer-subscription">
                                        <p>
                                            <input id="mc4wp_email" class="form-control" required="" placeholder="Enter Your Email"
                                                name="EMAIL" type="email">
                                        </p>
                                        <p>
                                            <input class="btn btn-default" value="Subscribe Now" type="submit">
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div> <!--  end .col-md-4 col-sm-12 -->
                        <div class="col-md-4 col-sm-6 col-xs-12">
                            <div class="footer-widget">
                                <div class="sidebar-widget-wrapper">
                                    <div class="footer-widget-header clearfix">
                                        <h3>Contact Us</h3>
                                    </div> <!--  end .footer-widget-header -->
                                    <div class="textwidget">
                                        <i class="fa fa-envelope-o fa-contact"></i>
                                        <p><a href="#">support@donation.com</a><br /><a href="#">helpme@donation.com</a></p>
                                        <i class="fa fa-location-arrow fa-contact"></i>
                                        <p>Road-2,3/A East Shibgonj<br />Sylhet-3100, Bangladesh</p>
    
                                        <i class="fa fa-phone fa-contact"></i>
                                        <p>Office:&nbsp; (+880) 0823 560 433<br />Cell:&nbsp; (+880) 0723 161 343</p>
                                    </div>
                                </div> <!-- end .footer-widget-wrapper  -->
                            </div> <!--  end .footer-widget  -->
                        </div> <!--  end .col-md-4 col-sm-12 -->
                        <div class="col-md-4 col-sm-12 col-xs-12">
                            <div class="footer-widget clearfix">
                                <div class="sidebar-widget-wrapper">
                                    <div class="footer-widget-header clearfix">
                                        <h3>Support Links</h3>
                                    </div> <!--  end .footer-widget-header -->
                                    <ul class="footer-useful-links">
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-caret-right fa-footer"></i>
                                                Thalassemia
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-caret-right fa-footer"></i>
                                                Cell Elofrosis
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-caret-right fa-footer"></i>
                                                Myelodysasia
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-caret-right fa-footer"></i>
                                                Blood Count
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-caret-right fa-footer"></i>
                                                Hemolytimia
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-caret-right fa-footer"></i>
                                                Ychromas Eosis
                                            </a>
                                        </li>
    
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-caret-right fa-footer"></i>
                                                Hyrcoagulable
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-caret-right fa-footer"></i>
                                                Thrombo Xtosis
                                            </a>
                                        </li>
    
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-caret-right fa-footer"></i>
                                                Sicklenemiaxs
                                            </a>
                                        </li>
    
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-caret-right fa-footer"></i>
                                                Aplastic Anemia
                                            </a>
                                        </li>
    
                                    </ul>
                                </div> <!--  end .footer-widget  -->
    
                            </div> <!--  end .footer-widget  -->
    
                        </div> <!--  end .col-md-4 col-sm-12 -->
                    </div> <!-- end row  -->
                </div> <!-- end .container  -->
            </section> <!--  end .footer-widget-area  -->
            <!--FOOTER CONTENT  -->
            <section class="footer-contents">
                <div class="container">
                    <div class="row clearfix">
                        <div class="col-md-6 col-sm-12">
                            <p class="copyright-text"> Copyright 2018, All Right Reserved - IamBloodDonor.com</p>
                        </div> <!-- end .col-sm-6  -->
                        <div class="col-md-6 col-sm-12 text-right">
                            <div class="footer-nav">
                                <nav>
                                    <ul>
                                        <li>
                                            <a href="index.html">Home</a>
                                        </li>
                                        <li>
                                            <a href="#">Causes</a>
                                        </li>
                                        <li>
                                            <a href="donate.html">Events</a>
                                        </li>
                                        <li>
                                            <a href="blog-with-sidebar.html">Gallery</a>
                                        </li>
                                        <li>
                                            <a href="campaign-grid.html">Blog</a>
                                        </li>
                                        <li>
                                            <a href="contact.html">Contact</a>
                                        </li>
                                    </ul>
                                </nav>
                            </div> <!--  end .footer-nav  -->
                        </div> <!--  end .col-lg-6  -->
                    </div> <!-- end .row  -->
                </div> <!--  end .container  -->
            </section> <!--  end .footer-content  -->
        </footer>
        <!-- END FOOTER  -->        

    

iamblooddonor/blooddonor/templates/blooddonor/gallery.html
{% extends "blooddonor/base.html" %} 
{% load static %}
{% block content %}
     <section class="galler_part">
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-lg-6">
                    <div class="about_content text-right">
                        <img src="{% static 'blooddonor/images/line.png' %} " alt="">
                        <h2>I'mBloodDonor  <span>Photo Gallery</span></h2>
                        <h4></h4>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center gallery_slider">

                <!-- gallery image slider start  -->
                {% for photo in photos %}
                <div class="col-lg-4">
                    <div class="gallery_img">
                        <img src="{{ photo.image.url }}" class="img-fluid" alt="">
                    </div>
                </div>
                {% endfor %}
                <!-- gallery image slider end  -->
            </div>
        </div>
    </section>
    <!-- gallery part end   -->

{% endblock content %}
    